// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using PodNet.Blazor.TypedRoutes;

namespace _2_PartialGeneratesAsExpected
{
    partial class MyComponent : IRoutableComponent, INavigableComponent
    {
        /// <summary>
        /// The primary route template for the component, the constant string <c>"/my-route"</c>.
        /// </summary>
        public static string PageRouteTemplate => "/my-route";

        /// <summary>
        /// All available route templates for the component, containing the string: <c>"/my-route</c>.
        /// </summary>
        public static IReadOnlyList<string> AllPageRouteTemplates { get; } = ImmutableArray.Create("/my-route");

        /// <summary>
        /// Returns the absolute page URI: <c>"/my-route"</c>.
        /// </summary>
        public static string PageUri => "/my-route";
    }
}
#nullable restore
