on: { push: { tags: ["*"] } }
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet pack -c:Release -p:Version=${{ github.ref_name }} -p:RepositoryCommit=${{ github.sha }}
      - env: { NUGET_API_KEY: "${{ secrets.NUGET_API_KEY }}" }
        run: dotnet nuget push ./src/TypedRoutes/bin/Release/PodNet.Blazor.TypedRoutes.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
